### ISSUE TITLE
classList.remove takes multiple parameters

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChromeLabs/web-a-skeb#13]
In line below: https://github.com/GoogleChromeLabs/web-a-skeb/blob/71bee9085381a8d82b02c1969444258f44499502/src/skeb-case.js#L201

you can use `this._screen.classList.remove('fanciest', 'fast');` to make it shorter.

**Comment by rowan-m** [comment]
Optimised. Thank you!
